(() => {
  'use strict';
  const VERSION='0.4.0';
  const PROVIDER='ESPN NFL SCOREBOARD + ESPN GAME SUMMARY + GOOGLE NEWS';
  const MAX_NEWS_AGE_HOURS=120;
  const normalize=s=>String(s??'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
  const uniq=a=>[...new Set((a||[]).filter(Boolean))];
  const num=(v,f=null)=>{const n=Number(v);return Number.isFinite(n)?n:f;};
  const freshnessBand=h=>h===null||h===undefined||!Number.isFinite(Number(h))?'UNKNOWN':Number(h)<=24?'FRESH':Number(h)<=72?'CURRENT':'STALE';
  function decodeXml(s){return String(s??'').replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n))).trim();}
  function tag(block,name){const m=String(block||'').match(new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${name}>`,'i'));return m?decodeXml(m[1]):null;}
  function scoreboardUrl(){return 'https://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard?limit=100';}
  function summaryUrl(gameId){return `https://site.api.espn.com/apis/site/v2/sports/football/nfl/summary?event=${encodeURIComponent(String(gameId||''))}`;}
  function depthChartUrl(teamId){return `https://site.api.espn.com/apis/site/v2/sports/football/nfl/teams/${encodeURIComponent(String(teamId||''))}/depthcharts`;}
  function depthRole(rank){if(rank===null||rank===undefined||rank==='')return'UNKNOWN';const r=Number(rank);return r===1?'STARTER':r===2?'ROTATION':Number.isFinite(r)?'DEPTH':'UNKNOWN';}
  function recordFor(c){const rs=c?.records||[];return rs.find(x=>x?.type==='total')?.summary||rs[0]?.summary||null;}
  function competitor(comp,side){return (comp?.competitors||[]).find(x=>x?.homeAway===side)||null;}
  function parseScoreboard(payload){
    const games=[];
    for(const e of payload?.events||[]){
      const c=e?.competitions?.[0]||{},away=competitor(c,'away'),home=competitor(c,'home');if(!away||!home)continue;
      const odds=c?.odds?.[0]||{},venue=c?.venue||{},weather=c?.weather||{},status=e?.status?.type||{};
      const teamObj=t=>({id:String(t?.team?.id||''),abbr:t?.team?.abbreviation||t?.team?.shortDisplayName||'',name:t?.team?.displayName||t?.team?.name||'',aliases:uniq([t?.team?.displayName,t?.team?.shortDisplayName,t?.team?.name,t?.team?.location]).filter(x=>normalize(x).length>=3),record:recordFor(t),score:t?.score??null});
      games.push({id:String(e?.id||c?.id||''),season:Number(payload?.season?.year||e?.season?.year)||null,week:Number(payload?.week?.number||e?.week?.number)||null,seasonType:Number(payload?.season?.type)||null,startAt:e?.date||c?.date||null,status:status?.name||status?.state||'SCHEDULED',statusDetail:status?.shortDetail||status?.detail||null,completed:!!status?.completed,away:teamObj(away),home:teamObj(home),venue:venue?.fullName||null,location:[venue?.address?.city,venue?.address?.state].filter(Boolean).join(', ')||null,broadcasts:(c?.broadcasts||[]).flatMap(x=>x?.names||[]),market:{provider:odds?.provider?.name||null,details:odds?.details||null,spread:num(odds?.spread),overUnder:num(odds?.overUnder)},weather:weather?.displayValue||null});
    }
    games.sort((a,b)=>String(a.startAt||'').localeCompare(String(b.startAt||'')));
    return{provider:'ESPN public scoreboard',status:games.length?'PASS':'ERROR',season:Number(payload?.season?.year)||games[0]?.season||null,week:Number(payload?.week?.number)||games[0]?.week||null,seasonType:Number(payload?.season?.type)||null,gameCount:games.length,games};
  }
  function statMap(teamBlock){const out={};for(const s of teamBlock?.statistics||[]){const k=s?.name||s?.label;if(k)out[k]=s?.displayValue??s?.value??null;}return out;}
  function teamAbbr(team){return team?.abbreviation||team?.shortDisplayName||team?.name||null;}
  function parseSummary(payload,{game=null}={}){
    const injuries=[];
    for(const b of payload?.injuries||[]){const team=teamAbbr(b?.team)||b?.team?.displayName||null;for(const x of b?.injuries||[]){const a=x?.athlete||{},pos=a?.position?.abbreviation||x?.position?.abbreviation||null,status=x?.status||x?.type?.description||x?.type?.name||null,type=x?.type?.abbreviation||x?.type?.name||null,details=x?.details||{};injuries.push({team,athleteId:String(a?.id||''),player:a?.displayName||a?.fullName||a?.shortName||null,position:pos,status,type,detail:details?.detail||details?.fantasyStatus||details?.returnDate||null,date:x?.date||null});}}
    const teamStats={};for(const b of payload?.boxscore?.teams||[]){const ab=teamAbbr(b?.team);if(ab)teamStats[ab]=statMap(b);}
    const leaders={};for(const b of payload?.leaders||[]){const ab=teamAbbr(b?.team);if(!ab)continue;leaders[ab]=(b?.leaders||[]).map(l=>({name:l?.name||l?.displayName||null,leaders:(l?.leaders||[]).slice(0,2).map(x=>({player:x?.athlete?.displayName||x?.athlete?.shortName||null,value:x?.displayValue||x?.value||null}))}));}
    const pc=(payload?.pickcenter||payload?.pickCenter||[])[0]||{};
    const market={provider:pc?.provider?.name||null,details:pc?.details||null,spread:num(pc?.spread),overUnder:num(pc?.overUnder)};
    const gi=payload?.gameInfo||{},weather=gi?.weather?.displayValue||gi?.weather?.conditionId||null,venue=gi?.venue?.fullName||null;
    const predictor=payload?.predictor||{};
    const predAway=num(predictor?.awayTeam?.gameProjection),predHome=num(predictor?.homeTeam?.gameProjection);
    return{status:'PASS',gameId:String(game?.id||payload?.header?.id||''),injuries,teamStats,leaders,market,weather,venue,predictor:Number.isFinite(predAway)&&Number.isFinite(predHome)?{away:predAway/100,home:predHome/100}:null};
  }

  function parseDepthChart(payload,{teamId=null,teamAbbr=null}={}){
    const rows=[];const charts=payload?.depthCharts||payload?.items||[];
    for(const chart of charts){for(const [slot,block] of Object.entries(chart?.positions||{})){const pos=block?.position||{};for(const entry of block?.athletes||[]){const a=entry?.athlete||{};const rank=num(entry?.rank??entry?.position?.rank,null);rows.push({teamId:String(teamId||''),teamAbbr:teamAbbr||null,chart:chart?.name||null,slot,position:pos?.abbreviation||pos?.name||null,athleteId:String(a?.id||'').replace(/.*\/(\d+).*/,'$1'),player:a?.displayName||a?.fullName||a?.shortName||null,rank,role:depthRole(rank)});}}}
    return{status:rows.length?'PASS':'EMPTY',teamId:String(teamId||''),teamAbbr:teamAbbr||null,rows};
  }
  function depthForInjury(x,depth){const rows=depth?.rows||[];const id=String(x?.athleteId||'');const name=normalize(x?.player);let matches=id?rows.filter(r=>String(r.athleteId||'')===id):[];if(!matches.length&&name)matches=rows.filter(r=>normalize(r.player)===name);if(!matches.length)return null;matches.sort((a,b)=>(num(a.rank,99)-num(b.rank,99)));return matches[0];}
  function positionWeight(group){return group==='QB'?5:group==='OL'?3.7:group==='RECEIVER'?3.2:group==='SECONDARY'?3.1:group==='FRONT7'?2.7:group==='BACKFIELD'?2.2:1.5;}

  const patterns={
    INJURY:/\b(injur(?:y|ed)|soreness|strain|sprain|concussion|hamstring|ankle|knee|shoulder|back|groin|foot)\b/i,
    INACTIVE:/\b(inactive|ruled out|will not play|won't play|out for|doubtful)\b|\brul(?:e|ed|es|ing)\b.{0,48}\bout\b/i,
    QUESTIONABLE:/\b(questionable|game time decision|game-time decision)\b/i,
    QB_CHANGE:/\b(starting quarterback|quarterback change|qb change|named starter|will start at quarterback|benched quarterback)\b/i,
    SUSPENSION:/\b(suspend(?:ed|sion)|disciplinary)\b/i,
    WEATHER:/\b(weather|rain|snow|wind|storm|lightning|heat|cold front)\b/i,
    LINE:/\b(spread|moneyline|total|odds|betting line)\b/i
  };
  function mentionsTeam(title,game){const n=` ${normalize(title)} `,aliases=uniq([...(game?.away?.aliases||[]),game?.away?.name,...(game?.home?.aliases||[]),game?.home?.name]).map(normalize).filter(x=>x.length>=3);return aliases.some(q=>q.includes(' ')?n.includes(` ${q} `):new RegExp(`(?:^|\\s)${q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}(?:$|\\s)`,'i').test(n));}
  function classifyTitle(title,game){const flags=Object.entries(patterns).filter(([,re])=>re.test(String(title||''))).map(([k])=>k),teamMention=mentionsTeam(title,game);let relevance='BACKGROUND';if(teamMention&&flags.some(x=>['INJURY','INACTIVE','QB_CHANGE','SUSPENSION','WEATHER'].includes(x)))relevance='DIRECTLY_MATERIAL';else if(teamMention&&flags.includes('QUESTIONABLE'))relevance='POSSIBLY_MATERIAL';return{flags,teamMention,relevance,reviewRequired:relevance==='DIRECTLY_MATERIAL'};}
  function fingerprint(title){const stop=new Set(['nfl','football','game','week','preview','prediction','predictions','pick','picks','odds','vs','at','the','a','an','and','or','for','to','on','in','of','with']);return normalize(title).split(' ').filter(w=>w.length>2&&!stop.has(w)).slice(0,14).sort().join('|');}
  function googleNewsUrl(game){const away=game?.away?.name||game?.away?.abbr,home=game?.home?.name||game?.home?.abbr,q=`("${away}" OR "${home}") NFL (injury OR inactive OR questionable OR quarterback OR suspension OR weather)`;return `https://news.google.com/rss/search?q=${encodeURIComponent(q)}&hl=en-US&gl=US&ceid=US:en`;}
  function parseGoogleNewsRss(xml,{game,nowMs=Date.now(),maxAgeHours=MAX_NEWS_AGE_HOURS}={}){const out=[],re=/<item\b[^>]*>([\s\S]*?)<\/item>/gi;let m;while((m=re.exec(String(xml||'')))){const b=m[1],title=tag(b,'title'),link=tag(b,'link'),pubDate=tag(b,'pubDate'),sm=b.match(/<source(?:\s+url="([^"]+)")?[^>]*>([\s\S]*?)<\/source>/i),sourceName=sm?decodeXml(sm[2]):null,t=Date.parse(pubDate||'');if(!title||!link)continue;const ageHours=Number.isFinite(t)?Math.max(0,(nowMs-t)/3600000):null;if(ageHours!==null&&ageHours>maxAgeHours)continue;const cls=classifyTitle(title,game),fp=fingerprint(title);out.push({title,link,publishedAt:Number.isFinite(t)?new Date(t).toISOString():null,ageHours,freshness:freshnessBand(ageHours),sourceName,sourceClass:'NEWS',fingerprint:fp,evidenceId:`NFL_NEWS:${game?.id||'game'}:${fp||normalize(title).slice(0,60)}`,...cls});}const seen=new Set();return out.filter(x=>{const k=x.fingerprint||normalize(x.title);if(seen.has(k))return false;seen.add(k);return true;}).slice(0,8);}
  function positionGroup(pos){const p=String(pos||'').toUpperCase();if(p==='QB')return'QB';if(['LT','RT','OT','T','LG','RG','OG','G','C','OL'].includes(p))return'OL';if(['WR','TE'].includes(p))return'RECEIVER';if(['RB','FB'].includes(p))return'BACKFIELD';if(['CB','S','FS','SS','DB'].includes(p))return'SECONDARY';if(['DE','EDGE','DT','NT','DL','LB','ILB','OLB'].includes(p))return'FRONT7';return'OTHER';}
  function injurySeverity(x){const status=normalize(`${x?.status||''} ${x?.type||''}`),pos=String(x?.position||'').toUpperCase(),group=positionGroup(pos),qb=group==='QB',rank=num(x?.depthRank,null),role=x?.depthRole||depthRole(rank),weight=positionWeight(group);if(/injured reserve|reserve injured|\bir\b/.test(status))return{level:'BACKGROUND',score:0,reason:'LONG_TERM_IR_BASELINE',group,role,rank,weight};const out=/inactive|ruled out|\bout\b|doubtful/.test(status),questionable=/questionable|game time|game-time/.test(status),roleMult=role==='STARTER'?1:role==='ROTATION'?.62:role==='DEPTH'?.32:.5,statusMult=out?1:questionable?.55:.2,impact=weight*roleMult*statusMult;if(qb&&(out||questionable))return{level:'DIRECT',score:Math.max(5,impact),reason:'QB_AVAILABILITY',group,role,rank,weight,impact};if(out&&role==='STARTER'&&weight>=3)return{level:'DIRECT',score:impact,reason:'STARTER_OUT_DOUBTFUL',group,role,rank,weight,impact};if((out||questionable)&&impact>=1)return{level:'POSSIBLE',score:impact,reason:out?'NON_QB_OUT_DOUBTFUL':'NON_QB_QUESTIONABLE',group,role,rank,weight,impact};return{level:'BACKGROUND',score:impact||0,reason:'ROUTINE_OR_UNRESOLVED',group,role,rank,weight,impact};}
  function injuryText(x){return [x?.player,x?.position?`(${x.position})`:null,x?.depthRole&&x.depthRole!=='UNKNOWN'?x.depthRole:null,x?.status||x?.type,x?.detail].filter(Boolean).join(' · ');}
  function injurySubject(x){return [x?.player,x?.team&&x?.position?`— ${x.team} ${x.position}`:x?.team?`— ${x.team}`:null,x?.status||x?.type].filter(Boolean).join(' · ');}
  function summarizeGameResearch(game,articles=[],summary=null,depthCharts={}){const current=(articles||[]).filter(a=>a.freshness!=='STALE'),direct=current.filter(a=>a.relevance==='DIRECTLY_MATERIAL'),possible=current.filter(a=>a.relevance==='POSSIBLY_MATERIAL'),background=(articles||[]).filter(a=>a.relevance==='BACKGROUND'||a.freshness==='STALE'),injuries=(summary?.injuries||[]).map(x=>{const d=depthForInjury(x,depthCharts?.[String(x.team||'').toUpperCase()]);const y={...x,depthRank:d?.rank??null,depthRole:d?.role||'UNKNOWN',depthPosition:d?.position||null};return{...y,severity:injurySeverity(y)};}),directInj=injuries.filter(x=>x.severity.level==='DIRECT'),possibleInj=injuries.filter(x=>x.severity.level==='POSSIBLE'),flags=uniq(direct.flatMap(a=>a.flags||[])),findings=[],subjects=[];
    const clusterMap=new Map();for(const x of possibleInj.filter(x=>x.severity.group!=='OTHER')){const key=`${x.team||'UNK'}:${x.severity.group}`;if(!clusterMap.has(key))clusterMap.set(key,[]);clusterMap.get(key).push(x);}const clusters=[...clusterMap.entries()].filter(([,xs])=>xs.length>=2&&xs.reduce((s,x)=>s+num(x.severity.score,0),0)>=3).map(([key,xs])=>({key,xs,team:xs[0]?.team||key.split(':')[0],group:xs[0]?.severity?.group||key.split(':')[1]}));
    for(const x of directInj.slice().sort((a,b)=>b.severity.score-a.severity.score).slice(0,3)){findings.push(`${injuryText(x)}.`);if(x.player)subjects.push(injurySubject(x));}
    for(const c of clusters.slice(0,2)){findings.push(`${c.team} has ${c.xs.length} current ${c.group} availability concerns (${c.xs.map(x=>x.player).filter(Boolean).join(', ')}).`);subjects.push(`${c.team} ${c.group} cluster — ${c.xs.length} players`);}
    for(const x of possibleInj.filter(x=>!clusters.some(c=>c.xs.includes(x))).slice(0,2)){findings.push(`${injuryText(x)}.`);if(x.player)subjects.push(injurySubject(x));}
    const add=(f,t)=>{if(flags.includes(f)&&!findings.includes(t))findings.push(t);};add('QB_CHANGE','Quarterback/starting-role news may materially change the matchup.');add('SUSPENSION','Current suspension/disciplinary availability news is present.');add('WEATHER','Current weather conditions may materially affect the game.');if(!findings.length&&direct.length){findings.push(`Direct headline: ${direct[0].title}`);subjects.push(direct[0].title);}if(!findings.length&&possible.length){findings.push(`Possible matchup context: ${possible[0].title}`);subjects.push(possible[0].title);}if(!findings.length)findings.push('No current directly material injury, inactive, quarterback-change, suspension, or weather finding was detected.');const review=directInj.length>0||direct.length>0||clusters.length>0,watch=!review&&(possibleInj.length>0||possible.length>0),impactLabel=subjects[0]||findings[0]||'No current material research flag.',teamImpact={};for(const x of injuries){if(x.severity.level==='BACKGROUND')continue;const t=String(x.team||'').toUpperCase();if(!t)continue;if(!teamImpact[t])teamImpact[t]={score:0,players:0,groups:{}};teamImpact[t].score+=num(x.severity.impact??x.severity.score,0);teamImpact[t].players++;const gr=x.severity.group||'OTHER';teamImpact[t].groups[gr]=(teamImpact[t].groups[gr]||0)+num(x.severity.impact??x.severity.score,0);}return{status:review?'REVIEW':watch?'WATCH':'NEUTRAL',directCount:direct.length+directInj.length+clusters.length,possibleCount:possible.length+possibleInj.length,backgroundCount:background.length+injuries.filter(x=>x.severity.level==='BACKGROUND').length,findings:findings.slice(0,6),keySubjects:uniq(subjects).slice(0,5),impactLabel,injuries:injuries.sort((a,b)=>b.severity.score-a.severity.score),personnel:{teamImpact,depthChartConnected:Object.values(depthCharts||{}).some(x=>x?.status==='PASS'),method:'STATUS_X_DEPTH_ROLE_X_POSITION_WEIGHT',probabilityMutation:false},articles:(articles||[]).slice(0,6),summary:summary||null,probabilityMutation:false};}
  function buildBoard(schedule,{newsResults=[],summaryResults=[],depthChartResults=[],updatedAt=null}={}){const newsById={},summaryById={},depthByTeam={};for(const r of newsResults||[])if(r?.gameId)newsById[String(r.gameId)]=r;for(const r of summaryResults||[])if(r?.gameId)summaryById[String(r.gameId)]=r;for(const r of depthChartResults||[]){const dc=r?.depthChart||r;if(dc?.teamAbbr)depthByTeam[String(dc.teamAbbr).toUpperCase()]=dc;}const games=(schedule?.games||[]).map(g=>{const nr=newsById[g.id]||{},sr=summaryById[g.id]||{},articles=nr.articles||[],summary=sr.summary||null,research=summarizeGameResearch(g,articles,summary,depthByTeam);return{...g,detail:summary,research};});return{provider:PROVIDER,version:VERSION,status:schedule?.status==='PASS'?'PASS':'ERROR',season:schedule?.season||null,week:schedule?.week||null,updatedAt:updatedAt||new Date().toISOString(),gameCount:games.length,depthChartTeamCount:Object.keys(depthByTeam).length,games,probabilityMutation:false};}
  const api={VERSION,PROVIDER,MAX_NEWS_AGE_HOURS,scoreboardUrl,summaryUrl,depthChartUrl,parseScoreboard,parseSummary,parseDepthChart,classifyTitle,googleNewsUrl,parseGoogleNewsRss,summarizeGameResearch,buildBoard,freshnessBand,fingerprint,injurySeverity,positionGroup,positionWeight};
  if(typeof window!=='undefined')window.MODEL_NFL_PUBLIC_CORE=api;
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
})();
