(() => {
  'use strict';
  const VERSION='0.2',PANEL_ID='modelTableProbePanelV02',RESULT_KEY='model_table_probe_v02_last';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function host(){const workflow=document.getElementById('workflowV1Root'),trust=document.getElementById('modelV2Root')||document.querySelector('[id*="modelV2"]'),anchor=workflow||trust||document.body.firstElementChild;if(!anchor?.parentNode)return null;let h=document.getElementById('modelTableProbeHostV02');if(!h){h=document.createElement('div');h.id='modelTableProbeHostV02';h.style.cssText='margin:0 16px 10px';}if(h.parentNode!==anchor.parentNode||h.nextSibling!==anchor)anchor.parentNode.insertBefore(h,anchor);return h;}
  function style(){if(document.getElementById('modelTableProbeStyleV02'))return;const s=document.createElement('style');s.id='modelTableProbeStyleV02';s.textContent=`#${PANEL_ID}{border:1px dashed #4b6b88;background:#0d141c;border-radius:11px;padding:10px;margin-bottom:8px;color:#d9e4ef;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif}#${PANEL_ID} .tp-head{display:flex;justify-content:space-between;gap:8px;align-items:center}.tp-title{font-size:11px;font-weight:850}.tp-badge{font-size:8px;background:#24394d;color:#bfe0ff;border-radius:999px;padding:3px 6px}.tp-sub{font-size:9px;color:#8ea0b2;margin:3px 0 8px;line-height:1.4}#${PANEL_ID} .tp-actions{display:grid;grid-template-columns:1fr 1fr 1fr;gap:6px}#${PANEL_ID} button{font-size:9px;padding:8px;border-radius:8px;background:#233446;color:#e9f4ff;border:1px solid #38536d}#${PANEL_ID} button.primary{background:#d8ebff;color:#0c1b2d;font-weight:800}#${PANEL_ID} .tp-status{font-size:9px;line-height:1.45;margin-top:7px;padding:7px;background:#0a1016;border-radius:7px;color:#9fd4aa;white-space:pre-wrap}.tp-status.bad{color:#ffaaaa}`;document.head.appendChild(s);}
  function render(msg='Deep probe ready. This version verifies main-world capture and inspects paging/RSC structure.',bad=false){style();const h=host();if(!h)return;let p=document.getElementById(PANEL_ID);if(!p){p=document.createElement('section');p.id=PANEL_ID;h.appendChild(p);}p.innerHTML=`<div class="tp-head"><div class="tp-title">DEV · PropsMadness Table Probe</div><div class="tp-badge">v${VERSION}</div></div><div class="tp-sub">Diagnostic only. No models or hydration. Captures current table rows, pagination candidates, Next/RSC script summaries and main-world request shapes.</div><div class="tp-actions"><button id="tpStart" class="primary">START DEEP CAPTURE</button><button id="tpSnapshot">RUN DEEP SNAPSHOT</button><button id="tpCopy">COPY LAST PROBE</button></div><div class="tp-status ${bad?'bad':''}">${esc(msg)}</div>`;p.querySelector('#tpStart')?.addEventListener('click',startCapture);p.querySelector('#tpSnapshot')?.addEventListener('click',runSnapshot);p.querySelector('#tpCopy')?.addEventListener('click',copyLast);}
  async function propsTab(){const tabs=await chrome.tabs.query({});const c=tabs.filter(t=>{try{return /(^|\.)propsmadness\.com$/i.test(new URL(t.url||'').hostname)&&/\/mlb\/props/i.test(t.url||'');}catch{return false;}});if(!c.length)throw new Error('No PropsMadness MLB props table tab found.');c.sort((a,b)=>(b.active?2:0)-(a.active?2:0));return c[0];}
  async function mainExec(tabId,func,args=[]){if(!chrome.scripting?.executeScript)throw new Error('chrome.scripting is required.');const out=await chrome.scripting.executeScript({target:{tabId},world:'MAIN',func,args});return out?.[0]?.result;}
  async function injectMain(tabId){await chrome.scripting.executeScript({target:{tabId},world:'MAIN',files:['propsmadness_table_probe_main.js']});}
  async function startCapture(){try{const t=await propsTab();await injectMain(t.id);const ok=await mainExec(t.id,()=>window.__MODEL_TABLE_PROBE_V02_START__?.()===true);if(!ok)throw new Error('Main-world hook did not verify.');render(`Deep capture VERIFIED on ${t.title}.\nSwitch among K → Outs → ER → Hits Allowed → Pitcher Walks. Then return to Strikeouts and RUN DEEP SNAPSHOT.`);}catch(e){render(e.message||String(e),true);}}
  function deepProbe(){
    const clean=s=>String(s||'').replace(/\s+/g,' ').trim(),text=clean(document.body?.innerText||''),countMatch=text.match(/(\d+)\s+of\s+(\d+)\s+props/i),gameMatch=text.match(/(\d+)\s+games/i);
    const tbody=document.querySelector('tbody'),table=tbody?.closest('table')||document.querySelector('table');
    const rows=[...document.querySelectorAll('tbody tr')].slice(0,80).map(el=>clean(el.innerText)).filter(Boolean);
    const headers=[...document.querySelectorAll('thead th,thead [role="columnheader"]')].map(el=>clean(el.innerText||el.getAttribute('aria-label'))).filter(Boolean);
    const candidates=[];
    for(const el of document.querySelectorAll('button,a,[role="button"]')){
      const label=clean(el.innerText||el.getAttribute('aria-label')||el.getAttribute('title')),href=el.tagName==='A'?el.href:null;
      if(!label&&!href)continue;
      const rect=el.getBoundingClientRect(),after=table?!!(table.compareDocumentPosition(el)&Node.DOCUMENT_POSITION_FOLLOWING):false;
      const interesting=/^(next|previous|prev|first|last|\d+|[›»→>‹«←<])$/i.test(label)||/page|pagination|next|previous/i.test(`${label} ${href||''} ${el.className||''}`);
      if(interesting)candidates.push({tag:el.tagName,label,aria:el.getAttribute('aria-label'),title:el.getAttribute('title'),href,disabled:!!el.disabled,afterTable:after,rect:{x:Math.round(rect.x),y:Math.round(rect.y),w:Math.round(rect.width),h:Math.round(rect.height)},className:String(el.className||'').slice(0,160)});
      if(candidates.length>=80)break;
    }
    const ancestry=[];let n=table;for(let i=0;n&&i<7;i++,n=n.parentElement)ancestry.push({tag:n.tagName,id:n.id||null,className:String(n.className||'').slice(0,180),children:n.children?.length||0});
    const scroll=[];for(const el of document.querySelectorAll('div,section,main')){const cs=getComputedStyle(el);if(!/(auto|scroll)/.test(cs.overflowY+cs.overflowX))continue;if(el.scrollHeight<=el.clientHeight+20&&el.scrollWidth<=el.clientWidth+20)continue;scroll.push({tag:el.tagName,id:el.id||null,className:String(el.className||'').slice(0,180),client:[el.clientWidth,el.clientHeight],scroll:[el.scrollWidth,el.scrollHeight]});if(scroll.length>=20)break;}
    const scripts=[...document.scripts];let nextFlightChars=0,nextFlightScripts=0;const scriptTerms={player:0,props:0,odds:0,line:0,strikeouts:0};for(const s of scripts){const x=s.textContent||'';if(!x.includes('__next_f.push'))continue;nextFlightScripts++;nextFlightChars+=x.length;const low=x.toLowerCase();for(const k of Object.keys(scriptTerms)){let p=0,c=0;while((p=low.indexOf(k,p))>=0){c++;p+=k.length;if(c>1000)break;}scriptTerms[k]+=c;}}
    const mem=performance.memory?{usedJSHeapMB:Math.round(performance.memory.usedJSHeapSize/1048576),totalJSHeapMB:Math.round(performance.memory.totalJSHeapSize/1048576),heapLimitMB:Math.round(performance.memory.jsHeapSizeLimit/1048576)}:null;
    return {probeVersion:'0.2',capturedAt:new Date().toISOString(),url:location.href,title:document.title,readyState:document.readyState,propsCount:countMatch?{shown:+countMatch[1],total:+countMatch[2]}:null,gameCount:gameMatch?+gameMatch[1]:null,table:{rowsInDom:rows.length,rowSamples:rows,headers,ancestry},paginationCandidates:candidates,scrollContainers:scroll,nextFlight:{scripts:nextFlightScripts,totalChars:nextFlightChars,termCounts:scriptTerms},resources:performance.getEntriesByType('resource').filter(r=>['fetch','xmlhttprequest'].includes(r.initiatorType)||/propsmadness\.com\/mlb\/props|_rsc=/i.test(r.name)).slice(-160).map(r=>({url:r.name,initiatorType:r.initiatorType,durationMs:Math.round(r.duration),transferSize:r.transferSize||0})),memory:mem};
  }
  async function runSnapshot(){try{const t=await propsTab();const base=(await chrome.scripting.executeScript({target:{tabId:t.id},func:deepProbe}))?.[0]?.result;if(!base)throw new Error('Deep DOM probe returned no result.');let cap=null;try{cap=await mainExec(t.id,()=>window.__MODEL_TABLE_PROBE_V02_READ__?.()||null);}catch{}base.mainWorldCapture=cap;await chrome.storage.local.set({[RESULT_KEY]:base});const n=cap?.events?.length||0;render(`Deep probe saved. DOM rows ${base.table?.rowsInDom||0}; page says ${base.propsCount?`${base.propsCount.shown}/${base.propsCount.total}`:'unknown'}; pagination candidates ${base.paginationCandidates?.length||0}; captured main-world events ${n}.\nCOPY LAST PROBE and paste it into ChatGPT.`);}catch(e){render(e.message||String(e),true);}}
  async function copyLast(){try{const obj=(await chrome.storage.local.get(RESULT_KEY))[RESULT_KEY];if(!obj)throw new Error('No v0.2 probe saved yet.');const txt='MODEL PROPSMADNESS TABLE PROBE v0.2\n'+JSON.stringify(obj,null,2);await navigator.clipboard.writeText(txt);render(`Copied ${txt.length.toLocaleString()} characters. Paste it into ChatGPT.`);}catch(e){render(e.message||String(e),true);}}
  function boot(){render();}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();setInterval(()=>{if(!document.getElementById(PANEL_ID))render();},2000);
})();
