(() => {
  'use strict';
  const VERSION='1.3';
  const MODEL_VERSION='mlb-moneyline-v0.8.0-offense-strength-2026-09-06';
  const CALIBRATION_STATUS='PRODUCTION_INPUT_MIGRATION';
  const METRIC_RANGES={
    'BA':[0.05,0.45],'xBA':[0.05,0.45],'xwOBA':[0.10,0.55],'xSLG':[0.10,0.90],
    'ISO':[0,0.60],'HardHit%':[10,70],'Barrel%':[0,30],'wRC+':[-100,300],
    'K%':[0,60],'BB%':[0,30],'Whiff%':[0,65],'Contact%':[35,100],'SwStr%':[0,35]
  };
  const num=(v,f=null)=>{if(v==null||v==='')return f;const n=Number(String(v).replace(/[^0-9.\-]/g,''));return Number.isFinite(n)?n:f;};
  const clamp=(x,lo,hi)=>Math.max(lo,Math.min(hi,x));
  const avg=a=>{const x=(a||[]).filter(Number.isFinite);return x.length?x.reduce((s,v)=>s+v,0)/x.length:null;};
  function strictNum(v,f=null){if(v==null)return f;const m=String(v).trim().match(/[-+]?(?:\d+(?:\.\d+)?|\.\d+)/);if(!m)return f;const n=Number(m[0]);return Number.isFinite(n)?n:f;}
  function metricNumber(o,k){const r=o?.[k];if(r==null||r==='-'||r==='')return null;return strictNum(r,null);}
  function validatedMetric(o,k,f=null){const n=metricNumber(o,k);if(!Number.isFinite(n))return f;const r=METRIC_RANGES[k];return !r||(n>=r[0]&&n<=r[1])?n:f;}
  function metricValidationReport(o={},label='metrics'){const invalid=[];let checked=0,valid=0;for(const [k,r] of Object.entries(o||{})){if(!(k in METRIC_RANGES)||r==null||r==='-'||r==='')continue;checked++;const n=strictNum(r),[lo,hi]=METRIC_RANGES[k];if(!Number.isFinite(n)||n<lo||n>hi)invalid.push(`${label} ${k}=${r}`);else valid++;}return{checked,valid,invalid,ok:!invalid.length};}
  function starterMetricValidation(s){const pitcher=metricValidationReport(s?.pitcherMetrics||{},'starter'),opponent=metricValidationReport(s?.opponentTeamMetrics||{},'opponent');const sf=r=>r.checked>=6&&(r.invalid.length>=3||r.invalid.length/Math.max(1,r.checked)>=.25);pitcher.schemaFailed=sf(pitcher);opponent.schemaFailed=sf(opponent);const invalid=[...pitcher.invalid,...opponent.invalid];return{ok:!invalid.length&&!pitcher.schemaFailed&&!opponent.schemaFailed,invalid,checked:pitcher.checked+opponent.checked,valid:pitcher.valid+opponent.valid,schemaIntegrityFailed:pitcher.schemaFailed||opponent.schemaFailed,pitcherSchemaFailed:pitcher.schemaFailed,opponentSchemaFailed:opponent.schemaFailed,pitcher,opponent};}
  function shrunkLineupMetric(row,key,leagueValue,shrinkPA=140){const raw=row?.metrics?.[key]??row?.[key],v=validatedMetric({[key]:raw},key,null);if(!Number.isFinite(v))return leagueValue;const pa=Math.max(0,strictNum(row?.PA,0)||0),r=pa/(pa+shrinkPA);return r*v+(1-r)*leagueValue;}
  function robustMean(arr){const xs=(arr||[]).filter(Number.isFinite).sort((a,b)=>a-b);if(!xs.length)return null;if(xs.length<6)return avg(xs);const t=Math.max(1,Math.floor(xs.length*.15)),k=xs.slice(t,xs.length-t);return avg(k.length?k:xs);}
  function lineupAverages(lineup=[]){const vm=(x,k)=>validatedMetric({[k]:x?.metrics?.[k]??x?.[k]},k,null);return{k:avg(lineup.map(x=>vm(x,'K%'))),bb:avg(lineup.map(x=>vm(x,'BB%'))),whiff:avg(lineup.map(x=>vm(x,'Whiff%'))),contact:avg(lineup.map(x=>vm(x,'Contact%'))),swstr:avg(lineup.map(x=>vm(x,'SwStr%'))),chase:avg(lineup.map(x=>vm(x,'Chase%'))),xwoba:avg(lineup.map(x=>vm(x,'xwOBA'))),xslg:avg(lineup.map(x=>vm(x,'xSLG'))),hardhit:avg(lineup.map(x=>vm(x,'HardHit%'))),barrel:avg(lineup.map(x=>vm(x,'Barrel%'))),n:lineup.length};}
  function weightedShrunkLineupMetric(lineup=[],key,baseline,shrinkPA=140){const w=[1.10,1.08,1.06,1.03,1,.98,.95,.92,.89];let sx=0,sw=0;(lineup||[]).slice(0,9).forEach((r,i)=>{const v=shrunkLineupMetric(r,key,baseline,shrinkPA);if(!Number.isFinite(v))return;sx+=v*(w[i]||.89);sw+=(w[i]||.89);});return sw?sx/sw:baseline;}
  function teamOffenseStrength(defenseCapture){const lineup=(defenseCapture?.lineup||[]).slice(0,9),n=lineup.length;if(!n)return{factor:1,rating:100,index:0,lineupRows:0,lineupStatus:defenseCapture?.lineupStatus||'Unknown',metrics:{wrc:100,iso:.170,xslg:.400,xwoba:.320,bb:8.5,k:22.5}};const wrc=weightedShrunkLineupMetric(lineup,'wRC+',100,160),iso=weightedShrunkLineupMetric(lineup,'ISO',.170,150),xslg=weightedShrunkLineupMetric(lineup,'xSLG',.400,150),xwoba=weightedShrunkLineupMetric(lineup,'xwOBA',.320,150),bb=weightedShrunkLineupMetric(lineup,'BB%',8.5,140),k=weightedShrunkLineupMetric(lineup,'K%',22.5,140);const index=clamp(.50*((wrc-100)/25)+.18*((iso-.170)/.055)+.12*((xslg-.400)/.065)+.08*((xwoba-.320)/.040)+.07*((bb-8.5)/3)-.05*((k-22.5)/5),-1.75,1.75);const coverage=clamp(n/9,0,1),officialWeight=/^official$/i.test(String(defenseCapture?.lineupStatus||''))?1:.72,raw=1+.085*index,factor=clamp(1+(raw-1)*coverage*officialWeight,.86,1.14);return{factor,rating:factor*100,index,lineupRows:n,lineupStatus:defenseCapture?.lineupStatus||'Unknown',metrics:{wrc,iso,xslg,xwoba,bb,k}};}
  function bullpenModel(rows,validation=null){const trusted=validation?.status==='cross_market_confirmed'||validation?.status==='validated_single_market'||validation?.status==='validated';if(!rows?.length||!trusted)return{era:4.20,whip:1.28,k:23,bb:8.5,freshness:.5,completeness:0};const era=robustMean(rows.map(r=>r.ERA))??4.2,whip=robustMean(rows.map(r=>r.WHIP))??1.28,k=robustMean(rows.map(r=>validatedMetric({'K%':r.K},'K%',null)))??23,bb=robustMean(rows.map(r=>validatedMetric({'BB%':r.BB},'BB%',null)))??8.5,used=rows.filter(r=>r.rest==='0').length,freshness=clamp((rows.length-used)/Math.max(rows.length,1),0,1),completeness=validation?.status==='cross_market_confirmed'?1:.70;return{era,whip,k,bb,freshness,completeness};}
  function parkRunFactor(gc=[]){for(let i=0;i<gc.length;i++){const m=`${gc[i]} ${gc[i+1]||''}`.match(/Runs\s*([+\-]\d+(?:\.\d+)?)%/i);if(m)return clamp(1+Number(m[1])/100,.85,1.15);}return 1;}
  function expectedRunsAgainstStarter(d,isHomeOffense=false,detail=false){const mv=starterMetricValidation(d),pm=mv.pitcherSchemaFailed?{}:(d?.pitcherMetrics||{}),om=mv.opponentSchemaFailed?{}:(d?.opponentTeamMetrics||{}),lu=lineupAverages(d?.lineup||[]),bp=bullpenModel(d?.bullpen||[],d?.bullpenValidation||null),off=teamOffenseStrength(d),ip=clamp(num(d?.workload?.IP,5.5),3.5,7);const pxw=validatedMetric(pm,'xwOBA',.320),oxw=validatedMetric(om,'xwOBA',lu.xwoba??.320),pba=validatedMetric(pm,'BA',.245),oba=validatedMetric(om,'BA',lu.ba??.245),pxslg=validatedMetric(pm,'xSLG',.400),oxslg=validatedMetric(om,'xSLG',lu.xslg??.400),phard=validatedMetric(pm,'HardHit%',39),ohard=validatedMetric(om,'HardHit%',lu.hardhit??39),pbarrel=validatedMetric(pm,'Barrel%',8),obarrel=validatedMetric(om,'Barrel%',lu.barrel??8),pk=validatedMetric(pm,'K%',22),pbb=validatedMetric(pm,'BB%',8),pwhiff=validatedMetric(pm,'Whiff%',25),ok=validatedMetric(om,'K%',lu.k??22),obb=validatedMetric(om,'BB%',lu.bb??8),ocontact=validatedMetric(om,'Contact%',lu.contact??75);let starterAdj=1;starterAdj+=(pxw-.320)*2.10+(pba-.245)*.75+(pxslg-.400)*.45+(phard-39)*.0025+(pbarrel-8)*.0040-(pk-22)*.0065-(pwhiff-25)*.0035+(pbb-8)*.009;let matchupAdj=(oxw-.320)*1.70+(oba-.245)*.55+(oxslg-.400)*.40+(ohard-39)*.0020+(obarrel-8)*.0030-(ok-22)*.0045+(obb-8)*.007+(ocontact-75)*.0025;starterAdj=clamp(starterAdj+matchupAdj*.35,.60,1.52);const starterR9=4.35*starterAdj*off.factor;let bullpenR9=.58*bp.era+.42*4.20;bullpenR9*=1+(bp.whip-1.28)*.18-(bp.k-23)*.004+(bp.bb-8.5)*.006;bullpenR9*=off.factor;bullpenR9*=1+(1-bp.freshness)*.05;bullpenR9=clamp(bullpenR9,2.7,6.6);const starterRuns=starterR9*ip/9,bullpenRuns=bullpenR9*(9-ip)/9,rawRunsBeforePark=starterRuns+bullpenRuns,parkFactor=parkRunFactor(d?.gameConditions||[]),homeFieldRuns=isHomeOffense?.20:0;let runs=rawRunsBeforePark*parkFactor+homeFieldRuns;runs=clamp(runs,1.8,7.5);return detail?{runs,starterRuns,bullpenRuns,rawRunsBeforePark,parkFactor,homeFieldRuns,expectedStarterIP:ip,starterR9,bullpenR9,starterAdj,matchupAdj,offenseFactor:off.factor,offenseRating:off.rating,offenseIndex:off.index,offenseMetrics:off.metrics,offenseLineupRows:off.lineupRows,offenseLineupStatus:off.lineupStatus,bullpen:bp}:runs;}
  function fairAmerican(p){p=clamp(p,.01,.99);return p>=.5?`-${Math.round(100*p/(1-p))}`:`+${Math.round(100*(1-p)/p)}`;}
  function predictionStrengthFromProbability(prob){const p=Math.max(Number(prob)||.5,1-(Number(prob)||.5));if(p<.525)return{label:'Toss-up',tier:0};if(p<.55)return{label:'Weak lean',tier:1};if(p<.58)return{label:'Moderate lean',tier:2};if(p<.62)return{label:'Strong',tier:3};if(p<.67)return{label:'Very strong',tier:4};return{label:'Exceptional',tier:5};}
  function projectGame(game){const {away,home}=game||{},awayStarter=game?.starters?.[away],homeStarter=game?.starters?.[home];if(!awayStarter||!homeStarter)return{complete:false,reason:'Need both starting-pitcher captures'};const a=expectedRunsAgainstStarter(homeStarter,false,true),h=expectedRunsAgainstStarter(awayStarter,true,true),diff=h.runs-a.runs,homeWin=1/(1+Math.exp(-diff/1.60)),awayWin=1-homeWin,strength=predictionStrengthFromProbability(Math.max(awayWin,homeWin)),favorite=awayWin>=homeWin?away:home;return{complete:true,awayRuns:a.runs,homeRuns:h.runs,awayWin,homeWin,awayOffenseRating:a.offenseRating,homeOffenseRating:h.offenseRating,awayOffenseFactor:a.offenseFactor,homeOffenseFactor:h.offenseFactor,awayOffenseIndex:a.offenseIndex,homeOffenseIndex:h.offenseIndex,awayOffenseMetrics:a.offenseMetrics,homeOffenseMetrics:h.offenseMetrics,awayRunComponents:a,homeRunComponents:h,awayFair:fairAmerican(awayWin),homeFair:fairAmerican(homeWin),predictionStrength:strength.label,predictionStrengthTier:strength.tier,favorite,favoriteProbability:Math.max(awayWin,homeWin),lineupCount:(awayStarter.lineup?.length||0)+(homeStarter.lineup?.length||0),modelVersion:MODEL_VERSION,engineVersion:VERSION,calibrationStatus:CALIBRATION_STATUS};}
  function structuredSavantRow(bundle,id,savantCore,{minCurrent=30,minPrevious=60}={}){const r=savantCore?.getRow?.(bundle,id,{minCurrent,minPrevious});if(!r)return null;return{mlbId:String(r.playerId),name:r.name||null,PA:num(r.pa,0),metrics:{'K%':r.kPct,'BB%':r.bbPct,'Whiff%':r.whiffPct,'Contact%':r.contactPct,'SwStr%':r.swStrPct,'BA':r.ba,'xBA':r.xba,'xSLG':r.xslg,'xwOBA':r.xwoba,'ISO':r.iso,'HardHit%':r.hardHitPct,'Barrel%':r.barrelPct,'wRC+':r.wrcPlus??null},sourceSeason:r.sourceSeason||null};}
  function workloadFromStarter(st,{allowSeasonFallback=true}={}){const outs=st?.markets?.['player-pitcher-outs'];const line=num(outs?.representative?.line,null),season=num(outs?.statistics?.overall?.season?.average,null);if(Number.isFinite(line))return{IP:line/3,expectedOuts:line,source:'PropsMadness current Pitcher Outs line',state:'CURRENT_GAME',productionEligible:true};if(allowSeasonFallback&&Number.isFinite(season))return{IP:season/3,expectedOuts:season,source:'PropsMadness Pitcher Outs season average (Radar/diagnostic only)',state:'SEASON_FALLBACK',productionEligible:false};return{IP:null,expectedOuts:null,source:'missing',state:'UNANCHORED',productionEligible:false};}
  function diagnosticGame(game){const d=JSON.parse(JSON.stringify(game||{}));for(const st of Object.values(d.starters||{})){for(const h of st.lineup||[]){if(!Number.isFinite(num(h.metrics?.['wRC+'],null))){if(!h.metrics)h.metrics={};h.metrics['wRC+']=100;h['wRC+']=100;}}}return d;}
  function getMapValue(map,key){return map instanceof Map?map.get(String(key)):map?.[String(key)];}
  function sourceFreshnessForGame(g,builtAt){const times=[];for(const side of ['away','home']){const st=g?.starters?.[side]||{};for(const m of Object.values(st?.markets||{})){const t=m?.capturedAt;if(t&&Number.isFinite(Date.parse(t)))times.push(t);}}if(builtAt&&Number.isFinite(Date.parse(builtAt)))times.push(builtAt);const ms=times.map(Date.parse).filter(Number.isFinite).sort((a,b)=>a-b);return{timestamps:[...new Set(times)],oldestCapturedAt:ms.length?new Date(ms[0]).toISOString():null,newestCapturedAt:ms.length?new Date(ms[ms.length-1]).toISOString():null,sourceCount:times.length};}
  function buildStructuredBoard({starterBoard,lineupsByPk,pitcherSavant,batterSavant,savantCore,wrcBundle=null,wrcCore=null,bullpensByTeam=null,parkBundle=null,parkCore=null,nowMs=Date.now()}){
    const builtAt=new Date(nowMs).toISOString();const games=[];let ready=0,blocked=0;
    const getLu=pk=>getMapValue(lineupsByPk,pk);
    for(const g of starterBoard?.games||[]){
      if(!g.pregame)continue;
      const reasons=[],watch=[],lu=getLu(g.gamePk)||{};
      const park=parkCore?.getForVenue?.(parkBundle,g.venueName)||null;
      if(!park) reasons.push('structured park/run-factor source unresolved');
      const parkConditions=park?parkCore.conditionLines(park):[];
      const game={gamePk:g.gamePk,away:g.away,home:g.home,awayTeamId:g.awayTeamId||null,homeTeamId:g.homeTeamId||null,venueId:g.venueId||null,venueName:g.venueName||null,startAt:g.startAt,starters:{},status:'BLOCKED',reasons,watchReasons:watch,sourceFreshness:sourceFreshnessForGame(g,builtAt),park:park?{provider:park.provider,providerVersion:park.providerVersion,venue:park.venue,window:park.window,rollingYears:park.rollingYears,runIndex:park.runIndex,runPct:park.runPct,runFactor:park.runFactor,pa:park.pa}:null};
      for(const side of ['away','home']){
        const st=g.starters?.[side]||{},opp=side==='away'?'home':'away',oppLu=lu?.[opp]||{state:'PENDING',hitters:[]};
        const teamCode=g[side],teamId=side==='away'?g.awayTeamId:g.homeTeamId;
        if(st.identityState!=='VERIFIED')reasons.push(`${side} starter identity not verified`);
        if(oppLu.state!=='OFFICIAL'||oppLu.hitters?.length!==9)reasons.push(`${side} opposing official lineup unavailable`);
        const p=structuredSavantRow(pitcherSavant,st.officialMlbId,savantCore,{minCurrent:30,minPrevious:60});
        if(!p)reasons.push(`${side} starter Savant row unavailable`);
        const hitters=[];
        for(const h of oppLu.hitters||[]){
          const r=structuredSavantRow(batterSavant,h.mlbId,savantCore,{minCurrent:20,minPrevious:80});
          if(!r)continue;
          const wr=wrcCore?.getForSavantRow?.(wrcBundle,h.mlbId,r)||null;
          const metrics={...(r.metrics||{}),'wRC+':Number.isFinite(num(wr?.wrcPlus,null))?Number(wr.wrcPlus):null};
          hitters.push({...r,order:h.order,batter:h.name||r.name,metrics,'wRC+':metrics['wRC+'],wrcSource:wr?{provider:'FanGraphs',season:wr.sourceSeason,seasonFallback:!!wr.seasonFallback,pa:wr.pa}:null});
        }
        if(hitters.length!==9)reasons.push(`${side} lineup Savant coverage ${hitters.length}/9`);
        const missingWrc=hitters.filter(h=>!Number.isFinite(num(h.metrics?.['wRC+'],null))).length;
        if(missingWrc)reasons.push(`${side} structured wRC+ source unresolved (${missingWrc}/9 hitters)`);
        const bp=getMapValue(bullpensByTeam,`${g.gamePk}:${side}`)||getMapValue(bullpensByTeam,teamCode)||getMapValue(bullpensByTeam,teamId);
        const bpValid=bp?.validation?.status==='validated'&&Array.isArray(bp?.rows)&&bp.rows.length>=4;
        if(!bpValid)reasons.push(`${side} structured bullpen source unresolved${bp?.validation?.reason?`: ${bp.validation.reason}`:''}`);
        const pm=p?.metrics||{},lineAvg=lineupAverages(hitters),baAvg=avg(hitters.map(x=>validatedMetric({'BA':x?.metrics?.BA??x?.BA},'BA',null)));
        const oppMetrics={'xwOBA':lineAvg.xwoba,'BA':baAvg,'xSLG':lineAvg.xslg,'HardHit%':lineAvg.hardhit,'Barrel%':lineAvg.barrel,'K%':lineAvg.k,'BB%':lineAvg.bb,'Contact%':lineAvg.contact};
        const workload=workloadFromStarter(st,{allowSeasonFallback:false});if(!workload.productionEligible)reasons.push(`${side} current Pitcher Outs line missing; production workload unanchored`);game.starters[teamCode]={side,team:teamCode,teamId:teamId||null,officialName:st.officialName,officialMlbId:st.officialMlbId,pitcherMetrics:pm,opponentTeamMetrics:oppMetrics,lineupStatus:oppLu.state==='OFFICIAL'?'Official':oppLu.state,lineup:hitters,workload,bullpen:bpValid?bp.rows:[],bullpenValidation:bpValid?bp.validation:{status:'missing_structured',reason:bp?.validation?.reason||'structured bullpen unavailable'},gameConditions:[...parkConditions]};
      }
      const diagnostic=diagnosticGame(game);
      const diagnosticProjection=projectGame(diagnostic);
      game.projectionEligible=reasons.length===0;
      if(game.projectionEligible){const productionProjection=projectGame(game);productionProjection.dataQuality='High';productionProjection.productionInputSource='STRUCTURED_ML_BOARD';productionProjection.calibrationStatus=CALIBRATION_STATUS;game.projection=productionProjection;game.status='READY';game.diagnosticProjection=productionProjection;game.diagnosticOnly=false;ready++;}
      else{game.projection=null;game.status='BLOCKED';game.diagnosticProjection=diagnosticProjection;game.diagnosticOnly=true;blocked++;}
      games.push(game);
    }
    return{schemaVersion:3,engineVersion:VERSION,modelVersion:MODEL_VERSION,calibrationStatus:CALIBRATION_STATUS,builtAt,gameCount:games.length,readyCount:ready,blockedCount:blocked,games};
  }
  function parity(oldProjection,newProjection,tol=1e-10){if(!oldProjection?.complete||!newProjection?.complete)return{pass:false,reason:'incomplete projection'};const fields=['awayRuns','homeRuns','awayWin','homeWin','awayOffenseFactor','homeOffenseFactor'];const deltas=Object.fromEntries(fields.map(k=>[k,Math.abs(Number(oldProjection[k])-Number(newProjection[k]))]));return{pass:Object.values(deltas).every(x=>Number.isFinite(x)&&x<=tol),tolerance:tol,deltas};}
  const api={VERSION,MODEL_VERSION,CALIBRATION_STATUS,METRIC_RANGES,validatedMetric,starterMetricValidation,shrunkLineupMetric,lineupAverages,teamOffenseStrength,bullpenModel,expectedRunsAgainstStarter,projectGame,structuredSavantRow,workloadFromStarter,diagnosticGame,sourceFreshnessForGame,buildStructuredBoard,parity};
  if(typeof window!=='undefined')window.MODEL_STRUCTURED_ML_CORE=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})();

