(() => {
  'use strict';
  const VERSION='1.4.0';
  const norm=s=>String(s??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]+/g,' ').replace(/\s+/g,' ').trim();
  function sameName(a,b){const aa=norm(a),bb=norm(b);if(!aa||!bb)return false;if(aa===bb)return true;const at=aa.split(' '),bt=bb.split(' ');return at.length>1&&bt.length>1&&at.at(-1)===bt.at(-1)&&at[0][0]===bt[0][0];}
  function trustForRow(edges,row){const xs=edges?.edges||[];if(row?.kind==='ML')return xs.find(e=>e.kind==='ML'&&String(e.gamePk)===String(row.gamePk))||null;return xs.find(e=>e.kind==='K'&&String(e.gamePk)===String(row.gamePk)&&String(e.projection?.officialMlbId||e.market?.officialMlbId||'')===String(row.officialMlbId||''))||xs.find(e=>e.kind==='K'&&String(e.gamePk)===String(row.gamePk)&&sameName(e.projection?.player||e.market?.player,row.player))||null;}
  function priorForRow(previous,row){return trustForRow(previous,row);}
  function mlbMatchups({starterBoard=null,radarBoard=null,edgeBoard=null,previousEdgeBoard=null,lineupBaselines=null}={}){const games=[];for(const g of starterBoard?.games||[]){const ml=(radarBoard?.ml||[]).find(r=>String(r.gamePk)===String(g.gamePk))||null,ks=(radarBoard?.k||[]).filter(r=>String(r.gamePk)===String(g.gamePk)),mlEdge=ml?trustForRow(edgeBoard,ml):null,mlPrevious=ml?priorForRow(previousEdgeBoard,ml):null,kRows=ks.map(r=>({row:r,edge:trustForRow(edgeBoard,r),previousEdge:priorForRow(previousEdgeBoard,r)}));const direct=(ml?.research?.publicResearch?.materialSummary?.directCount||0)+kRows.reduce((s,x)=>s+(x.row?.research?.publicResearch?.materialSummary?.directCount||0),0),possible=(ml?.research?.publicResearch?.materialSummary?.possibleCount||0)+kRows.reduce((s,x)=>s+(x.row?.research?.publicResearch?.materialSummary?.possibleCount||0),0);games.push({league:'MLB',id:String(g.gamePk),gamePk:String(g.gamePk),away:g.away,home:g.home,startAt:g.startAt,venue:g.venueName||null,state:g.state||null,pregame:!!g.pregame,lineups:g.lineups||null,starters:{away:g.starters?.away||null,home:g.starters?.home||null},ml:{row:ml,edge:mlEdge,previousEdge:mlPrevious,lineupBaseline:lineupBaselines?.[String(g.gamePk)]||null},k:kRows,researchSummary:{status:direct?'REVIEW':possible?'WATCH':'NEUTRAL',directCount:direct,possibleCount:possible}});}games.sort((a,b)=>String(a.startAt||'').localeCompare(String(b.startAt||'')));return{version:VERSION,league:'MLB',status:games.length?'PASS':'EMPTY',builtAt:radarBoard?.researchUpdatedAt||radarBoard?.builtAt||starterBoard?.capturedAt||null,gameCount:games.length,games};}
  const nflAlias={WAS:'WSH',WSH:'WSH',LA:'LAR',LAR:'LAR'};
  const nflAbbr=s=>nflAlias[String(s||'').toUpperCase()]||String(s||'').toUpperCase();
  function omegaForGame(omegaBoard,away,home){const a=nflAbbr(away),h=nflAbbr(home);return (omegaBoard?.games||[]).find(g=>nflAbbr(g.away)===a&&nflAbbr(g.home)===h)||null;}
  function nflMatchups(nflBoard,omegaBoard=null){const games=(nflBoard?.games||[]).map(g=>({league:'NFL',id:String(g.id),away:g.away?.abbr||g.away?.name,home:g.home?.abbr||g.home?.name,startAt:g.startAt,raw:g,omega:omegaForGame(omegaBoard,g.away?.abbr||g.away?.name,g.home?.abbr||g.home?.name),researchSummary:g.research||{status:'NEUTRAL'}}));return{version:VERSION,league:'NFL',status:nflBoard?.status||'EMPTY',season:nflBoard?.season||null,week:nflBoard?.week||null,builtAt:nflBoard?.updatedAt||null,omegaStatus:omegaBoard?.status||'NOT_AVAILABLE',omegaLedgerId:omegaBoard?.probabilityLedgerId||null,omegaMarketComparisonId:omegaBoard?.marketComparisonId||null,gameCount:games.length,games};}
  const api={VERSION,mlbMatchups,nflMatchups,trustForRow,omegaForGame};
  if(typeof window!=='undefined')window.MODEL_MATCHUP_CORE=api;
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
})();
