(() => {
  'use strict';
  const VERSION='0.2.0';
  const num=(v,f=null)=>{const n=Number(v);return Number.isFinite(n)?n:f;};
  const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
  const other=(g,side)=>side===g?.away?g?.home:side===g?.home?g?.away:null;
  const pct=v=>Number.isFinite(Number(v))?`${(Number(v)*100).toFixed(1)}%`:'—';
  function pushEdge(out,component,side,magnitude,text,source='DERIVED'){if(!side||!Number.isFinite(Number(magnitude))||Math.abs(Number(magnitude))<1e-9)return;out.push({component,side,magnitude:Math.abs(Number(magnitude)),text,source});}
  function lineupNames(s){return (s?.players||[]).map(x=>String(x?.name||'').trim()).filter(x=>x&&x!=='League-average proxy');}
  function lineupTransition(g,ml,proj){const b=g?.ml?.lineupBaseline,c=ml?.lineupSnapshot;if(!c)return{status:'UNAVAILABLE',reason:'Current lineup snapshot unavailable.'};const out={status:b?'CONNECTED':'BASELINE_PENDING',capturedAt:b?.capturedAt||null,teams:{},selectedSideDeltaPP:null,probabilityMutation:false};for(const [key,team] of [['away',g.away],['home',g.home]]){const cur=c?.[key]||{},base=b?.lineupSnapshot?.[key]||null,curNames=lineupNames(cur),baseNames=lineupNames(base),added=curNames.filter(x=>!baseNames.includes(x)),removed=baseNames.filter(x=>!curNames.includes(x)),curOff=num(key==='away'?proj?.awayOffenseRating:proj?.homeOffenseRating),baseOff=num(key==='away'?b?.projection?.awayOffenseRating:b?.projection?.homeOffenseRating),curRuns=num(key==='away'?proj?.awayRuns:proj?.homeRuns),baseRuns=num(key==='away'?b?.projection?.awayRuns:b?.projection?.homeRuns);out.teams[team]={team,key,official:!!cur.official,source:cur.source||null,coverage:num(cur.coverage,null),players:cur.players||[],added,removed,offenseRatingDelta:curOff!==null&&baseOff!==null?curOff-baseOff:null,projectedRunsDelta:curRuns!==null&&baseRuns!==null?curRuns-baseRuns:null,baselineSource:base?.source||null};}if(b){const side=ml?.side;if(side===g.away||side===g.home){const curr=side===g.away?num(proj?.awayWin):num(proj?.homeWin),base=side===g.away?num(b?.projection?.awayWin):num(b?.projection?.homeWin);if(curr!==null&&base!==null)out.selectedSideDeltaPP=(curr-base)*100;}}return out;}
  function mlbIntelligence(g){const ml=g?.ml?.row,edge=g?.ml?.edge,proj=edge?.projection||ml?.projection||{},q=ml?.research||{},side=ml?.side||edge?.trust?.side?.team||null,opp=other(g,side),edges=[],risks=[];if(!ml||!side)return{version:VERSION,sport:'MLB',status:'INSUFFICIENT',quality:'LOW',lean:null,edges:[],support:[],opposition:[],risks:['Production ML row unavailable.'],summary:'Matchup intelligence unavailable because the MLB moneyline model row is missing.',probabilityMutation:false};
    const selectedAway=side===g.away,selRuns=num(selectedAway?proj.awayRuns:proj.homeRuns),oppRuns=num(selectedAway?proj.homeRuns:proj.awayRuns);if(selRuns!==null&&oppRuns!==null){const d=selRuns-oppRuns;pushEdge(edges,'PROJECTED RUNS',d>=0?side:opp,Math.abs(d),`${d>=0?side:opp} projected-run advantage ${Math.abs(d).toFixed(2)} runs`,'ML_RUN_MODEL');}
    const selOff=num(selectedAway?proj.awayOffenseRating:proj.homeOffenseRating),oppOff=num(selectedAway?proj.homeOffenseRating:proj.awayOffenseRating);if(selOff!==null&&oppOff!==null){const d=selOff-oppOff;pushEdge(edges,'OFFENSE',d>=0?side:opp,Math.abs(d)/8,`${d>=0?side:opp} offense rating advantage ${Math.abs(d).toFixed(1)} points`,'ML_OFFENSE');}
    const awayRC=proj.awayRunComponents||ml?.modelComponents?.runModel?.away||{},homeRC=proj.homeRunComponents||ml?.modelComponents?.runModel?.home||{};
    const selectedStarterAllowed=num(selectedAway?homeRC.starterRuns:awayRC.starterRuns),opponentStarterAllowed=num(selectedAway?awayRC.starterRuns:homeRC.starterRuns);if(selectedStarterAllowed!==null&&opponentStarterAllowed!==null){const winner=selectedStarterAllowed<=opponentStarterAllowed?side:opp,adv=Math.abs(selectedStarterAllowed-opponentStarterAllowed);pushEdge(edges,'STARTING PITCHING',winner,adv*1.3,`${winner} starter run-prevention edge ${adv.toFixed(2)} projected runs`,'ML_STARTER');}
    const selectedBullpenAllowed=num(selectedAway?homeRC.bullpenRuns:awayRC.bullpenRuns),opponentBullpenAllowed=num(selectedAway?awayRC.bullpenRuns:homeRC.bullpenRuns);if(selectedBullpenAllowed!==null&&opponentBullpenAllowed!==null){const winner=selectedBullpenAllowed<=opponentBullpenAllowed?side:opp,adv=Math.abs(selectedBullpenAllowed-opponentBullpenAllowed);pushEdge(edges,'BULLPEN',winner,adv*1.2,`${winner} bullpen run-prevention edge ${adv.toFixed(2)} projected runs`,'ML_BULLPEN');}
    const rf=q.recentForm||{},a=rf.team,b=rf.opponent;if(a?.games&&b?.games){const aw=(num(a.wins,0)/Math.max(1,num(a.games,1))),bw=(num(b.wins,0)/Math.max(1,num(b.games,1))),ard=num(a.runDiff,0)/Math.max(1,num(a.games,1)),brd=num(b.runDiff,0)/Math.max(1,num(b.games,1)),d=(aw-bw)*2+(ard-brd)/5;pushEdge(edges,'RECENT FORM',d>=0?side:opp,Math.abs(d),`${d>=0?side:opp} recent-form advantage · ${side} ${a.wins}-${a.losses} / ${opp} ${b.wins}-${b.losses}`,'RCE_RECENT_FORM');}
    const marketEdge=num(edge?.trust?.side?.edge);if(marketEdge!==null&&marketEdge!==0)pushEdge(edges,'MODEL VS SHARP',marketEdge>=0?side:opp,Math.abs(marketEdge)*10,`${marketEdge>=0?side:opp} model-vs-sharp edge ${(Math.abs(marketEdge)*100).toFixed(1)}pp`,'TRUST');
    const x=q.externalProjections||{};if(x.status==='CONNECTED'){const favored=x.favorite||null;if(favored)pushEdge(edges,'INDEPENDENT PROJECTION',favored,Math.abs(num(x.selectedSideProbability,.5)-.5)*2,`${x.provider||'Independent projection'} favors ${favored}${favored===x.selectedSide?` ${pct(x.selectedSideProbability)}`:''}`,'EXTERNAL');if(x.assessment==='MAJOR_CONFLICT')risks.push(`Independent projection major conflict · model/external gap ${Math.abs(num(x.modelDeltaPP,0)).toFixed(1)}pp.`);}
    const lineupImpact=lineupTransition(g,ml,proj);if(lineupImpact.status==='CONNECTED'){const t=lineupImpact.teams?.[side];if(t?.offenseRatingDelta!==null){const d=t.offenseRatingDelta;pushEdge(edges,'LINEUP IMPACT',d>=0?side:opp,Math.abs(d)/8,`${side} official-lineup offense rating ${d>=0?'+':''}${d.toFixed(1)} vs pre-lineup baseline`,'LINEUP_TRANSITION');}if(lineupImpact.selectedSideDeltaPP!==null&&Math.abs(lineupImpact.selectedSideDeltaPP)>=.2){const d=lineupImpact.selectedSideDeltaPP;pushEdge(edges,'LINEUP PROBABILITY MOVE',d>=0?side:opp,Math.abs(d)/5,`${side} model probability moved ${d>=0?'+':''}${d.toFixed(1)}pp after lineup transition`,'LINEUP_TRANSITION');}}
    for(const r of edge?.trust?.reasons||[])risks.push(String(r));if((ml.officialLineups??0)<2)risks.push(`Official lineups incomplete: ${ml.officialLineups??0}/2.`);if(q.publicResearch?.reviewRequired)risks.push('Current sourced research requires review.');
    const support=edges.filter(x=>x.side===side).sort((a,b)=>b.magnitude-a.magnitude),opposition=edges.filter(x=>x.side===opp).sort((a,b)=>b.magnitude-a.magnitude),trust=edge?.trust?.state||ml.stage||'RADAR';let quality='MEDIUM';if(trust==='VERIFIED'&&(ml.officialLineups??0)===2&&!risks.some(r=>/major conflict|requires review/i.test(r)))quality='HIGH';if(['BLOCKED','ANOMALY','PASS'].includes(trust)||risks.some(r=>/major conflict/i.test(r)))quality='LOW';const summary=`${side} leads ${support.length} measured component${support.length===1?'':'s'} vs ${opp} ${opposition.length}; ${risks.length?`primary uncertainty: ${risks[0]}`:'no major derived uncertainty is currently flagged.'}`;return{version:VERSION,sport:'MLB',status:'PASS',lean:side,opponent:opp,quality,trustState:trust,edges:edges.sort((a,b)=>b.magnitude-a.magnitude),support,opposition,risks:[...new Set(risks)].slice(0,6),lineupImpact,summary,probabilityMutation:false};}
  function spreadFavorite(details){const m=String(details||'').toUpperCase().match(/\b([A-Z]{2,3})\s+([+-]?\d+(?:\.\d+)?)/);if(!m)return null;const line=Number(m[2]);return Number.isFinite(line)&&line<0?{team:m[1],line}:null;}
  const unitTarget={QB:'DEFENSIVE MATCHUP',OL:'PASS RUSH / TRENCHES',RECEIVER:'PASS COVERAGE',BACKFIELD:'RUN DEFENSE',SECONDARY:'PASSING GAME',FRONT7:'RUN GAME / PROTECTION',OTHER:'DEPTH'};
  function nflIntelligence(g){const r=g?.raw||{},q=r.research||{},detail=r.detail||q.summary||{},edges=[],risks=[],votes=[];const away=g?.away,home=g?.home,pred=detail.predictor;if(pred&&num(pred.away)!==null&&num(pred.home)!==null){const side=num(pred.away)>=num(pred.home)?away:home,p=Math.max(num(pred.away),num(pred.home));pushEdge(edges,'ESPN PREDICTOR',side,Math.abs(p-.5)*2,`ESPN predictor favors ${side} ${pct(p)}`,'PUBLIC_PREDICTOR');votes.push(side);}
    const fav=spreadFavorite(detail.market?.details||r.market?.details);if(fav){pushEdge(edges,'PUBLIC MARKET',fav.team,clamp(Math.abs(fav.line)/14,0,1.5),`Public market lists ${fav.team} ${fav.line}`,'PUBLIC_MARKET');votes.push(fav.team);}
    const teamImpact=q.personnel?.teamImpact||{},ab=num(teamImpact[String(away||'').toUpperCase()]?.score,0),hb=num(teamImpact[String(home||'').toUpperCase()]?.score,0);if(Math.abs(ab-hb)>=.35){const side=ab<hb?away:home;pushEdge(edges,'PERSONNEL AVAILABILITY',side,Math.abs(ab-hb)/4,`${side} availability edge · weighted personnel impact ${Math.min(ab,hb).toFixed(1)} vs ${Math.max(ab,hb).toFixed(1)}`,'DEPTH_CHART_INJURY');votes.push(side);}
    const grouped={};for(const x of q.injuries||[]){if(x.severity?.level==='BACKGROUND')continue;const team=String(x.team||'').toUpperCase(),group=x.severity?.group||'OTHER',impact=num(x.severity?.impact??x.severity?.score,0);if(!team||impact<=0)continue;const k=`${team}:${group}`;if(!grouped[k])grouped[k]={team,group,impact:0,players:[]};grouped[k].impact+=impact;grouped[k].players.push(x);}for(const z of Object.values(grouped)){if(z.impact<1.5)continue;const beneficiary=String(z.team).toUpperCase()===String(away).toUpperCase()?home:away,names=z.players.slice(0,2).map(x=>`${x.player||'player'}${x.depthRole&&x.depthRole!=='UNKNOWN'?` (${x.depthRole.toLowerCase()})`:''}`).join(', ');pushEdge(edges,unitTarget[z.group]||'PERSONNEL MATCHUP',beneficiary,z.impact/5,`${beneficiary} personnel pressure point vs ${z.team} ${z.group}: ${names}`,'DEPTH_CHART_INJURY');}
    if(q.status==='REVIEW')risks.push(q.impactLabel||q.findings?.[0]||'Current directly material research requires review.');else if(q.status==='WATCH')risks.push(q.impactLabel||q.findings?.[0]||'Possible matchup context requires monitoring.');if((q.articles||[]).some(a=>(a.flags||[]).includes('WEATHER')&&a.freshness!=='STALE'))risks.push('Current weather research may materially affect the game.');
    const omega=g?.omega||null,actionable=omega?.counts?.actionable??(omega?.marketRows||[]).filter(x=>x.actionability==='ACTIONABLE').length,omegaStatus=!omega?'NOT_AVAILABLE':actionable>0?'MARKET_READY':'PREGAME_NOT_ACTIONABLE';if(omegaStatus==='PREGAME_NOT_ACTIONABLE')risks.push('OMEGA tackle layer is pre-gameday / not actionable.');
    const tally={};for(const v of votes)if(v)tally[v]=(tally[v]||0)+1;const ranked=Object.entries(tally).sort((a,b)=>b[1]-a[1]),publicLean=ranked.length&&(!ranked[1]||ranked[0][1]>ranked[1][1])?ranked[0][0]:null;const dataSignals=edges.length;let quality=dataSignals>=3?'HIGH':dataSignals>=1?'MEDIUM':'LOW';if(q.personnel?.depthChartConnected&&quality==='MEDIUM')quality='MEDIUM-HIGH';const summary=publicLean?`Public/research context leans ${publicLean} on ${ranked[0][1]} of ${votes.length} directional signals. Personnel weighting uses injury status, depth-chart role and position importance. This is not a MODEL game-side pick.`:'Public/research context has no directional consensus. Personnel context remains descriptive and is not a MODEL game-side pick.';return{version:VERSION,sport:'NFL',status:dataSignals?'PASS':'INSUFFICIENT',publicLean,quality,edges:edges.sort((a,b)=>b.magnitude-a.magnitude),risks:[...new Set(risks)].slice(0,6),personnel:{teamImpact,depthChartConnected:!!q.personnel?.depthChartConnected},omega:{status:omegaStatus,actionable},summary,probabilityMutation:false,gameSideModel:false};}
  const api={VERSION,mlbIntelligence,nflIntelligence,spreadFavorite,lineupTransition};
  if(typeof window!=='undefined')window.MODEL_MATCHUP_INTELLIGENCE=api;
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
})();
